export const mockUserData = {
    "login": "ingenious091",
    "id": 157160200,
    "node_id": "U_kgDOCV4TCA",
    "avatar_url": "https://avatars.githubusercontent.com/u/157160200?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ingenious091",
    "html_url": "https://github.com/ingenious091",
    "followers_url": "https://api.github.com/users/ingenious091/followers",
    "following_url": "https://api.github.com/users/ingenious091/following{/other_user}",
    "gists_url": "https://api.github.com/users/ingenious091/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ingenious091/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ingenious091/subscriptions",
    "organizations_url": "https://api.github.com/users/ingenious091/orgs",
    "repos_url": "https://api.github.com/users/ingenious091/repos",
    "events_url": "https://api.github.com/users/ingenious091/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ingenious091/received_events",
    "type": "User",
    "site_admin": false,
    "name": null,
    "company": null,
    "blog": "",
    "location": "Roorkee, Uttarakhand",
    "email": null,
    "hireable": null,
    "bio": "Enjoy life.",
    "twitter_username": "ingenious091",
    "public_repos": 7,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2024-01-19T18:33:58Z",
    "updated_at": "2024-04-22T10:43:36Z"
};